version: "3.5"

services:

  app:
    build: ../
    image: nightlybuilders/react-boilerplate:dev
    environment:
      NODE_ENV: "development"
      API_HOSTS: "https://jsonplaceholder.typicode.com/"
      GQL_HOSTS: "https://w5xlvm3vzz.lp.gql.zone/graphql"
      STATIC_CACHE_EXPIRATION_TIME: 60
      STATIC_CACHE_PRIVACY: "private"
      DEBUG: "*"
      LOG_OPS: "TRUE"
      BASIC_USER: "john"
      BASIC_PW: "doe"
    ports:
      - "8000:8000"
