version: "3.5"

services:

  app:
    build: ../
    image: nightlybuilders/react-boilerplate:dev
    environment:
      NODE_ENV: "development"
      STATIC_CACHE_EXPIRATION_TIME: 60
      STATIC_CACHE_PRIVACY: "private"
      LOG_OPS: "TRUE"
      BASIC_USER: "john"
      BASIC_PW: "doe"
    ports:
      - "8000:8000"
